from django.urls import path
from django.conf.urls import url
from . import views
from .views import *
from django.contrib.auth.decorators import login_required, permission_required

app_name = "Formularios"
urlpatterns = [
    path('beneficiarios/<int:beneficiario>/evidencias/registrar', EvidenciaCreate.as_view(),
         name='evidencias_register'),
    path('beneficiarios/<int:beneficiario>/evidencias/', EvidenciaView.as_view(),
         name='view_evidencias'),
    path('beneficiarios/<int:beneficiario>/hemoglobinaglucosilada/registrar',
         login_required(HemoglobinaGlucosiladaCreate.as_view()),
         name='register_hemoglobinaglucosilada'),
    path('beneficiarios/<int:beneficiario>/microalbuminuria/registrar', MicroalbuminuriaCreate.as_view(),
         name='register_microalbuminuria'),
    path('beneficiarios/<int:beneficiario>/quimicasanguinea/registrar',
         login_required(QuimicaSanguineaCreate.as_view()), name='cqs'),
    path('quimicasanguinea/<int:pk>/eliminar', QuimicaSanguineaDelete.as_view(), name="delete_quimicasanguinea"),
    path('beneficiarios/<int:beneficiario>/glucosacapilar/registrar', GlucosaCapilarCreate.as_view(),
         name='register_glucosacapilar'),
    path('beneficiarios/<int:beneficiario>/malnutricioninflamacion/registrar', MalnutricionInflamacionCreate.as_view(),
         name='register_malnutricioninflamacion'),
    path('beneficiarios/<int:beneficiario>/clasificacion/registrar', ClasificacionCreate.as_view(),
         name='clasificacion_register'),

    path('beneficiarios/<int:beneficiario>/factorderiesgo/registrar', FactorDeRiesgoCreate.as_view(),
         name='register_factorderiesgo'),
    path('beneficiarios/<int:beneficiario>/tamizajenutricional/registrar', TamizajeNutricionalCreate.as_view(),
         name='register_tamizajenutricional'),
    path('beneficiarios/<int:beneficiario>/adherenciatratamiento/registrar', AdherenciaTratamientoCreate.as_view(),
         name='register_adherenciatratamiento'),
    path('adherenciatratamiento/<int:adherenciatratamiento>',
         AdherenciaTratamientoView.as_view(), name="view_adherenciatratamiento"),
    path('factorderiesgo/<int:factorderiesgo>',
         FactorDeRiesgoView.as_view(), name="view_factorderiesgo"),
    path('hemoglobinaglucosilada/<int:hemoglobinaglucosilada>',
         HemoglobinaGlucosiladaView.as_view(), name="view_hemoglobinaglucosilada"),
    path('malnutricioninflamacion/<int:malnutricioninflamacion>',
         MalnutricionInflamacionView.as_view(), name="view_malnutricioninflamacion"),
    path('malnutricioninflamacion/<int:pk>/eliminar',
         MalnutricionInflamacionDelete.as_view(), name="delete_malnutricioninflamacion"),
    path('microalbuminuria/<int:microalbuminuria>', MicroalbuminuriaView.as_view(), name="view_microalbuminuria"),
    path('microalbuminuria/<int:pk>/eliminar', MicroalbuminuriaDelete.as_view(), name="delete_microalbuminuria"),
    path('quimicasanguinea/<int:quimicaSanguinea>', QuimicaSanguineaView.as_view(), name='vqs'),
    path('glucosacapilar/<int:glucosacapilar>', GlucosaCapilarView.as_view(), name="view_glucosacapilar"),
    path('tamizajenutricional/<int:tamizajenutricional>',
         TamizajeNutricionalView.as_view(), name="view_tamizajenutricional"),
    path('beneficiarios/<int:beneficiario>/escalahamilton/registrar', EscalaHamiltonCreate.as_view(),
         name='register_escalahamilton'),
    path('escalahamilton/<int:escalaHamilton>',
         EscalaHamiltonView.as_view(), name="view_escalahamilton"),
    path('beneficiarios/<int:beneficiario>/consultamedica/registrar', ConsultaMedicaCreate.as_view(),
         name='register_consultamedica'),
    path('consultamedica/<int:consultamedica>',
         ConsultaMedicaView.as_view(), name="view_consultamedica"),
    path('consultamedica/<int:pk>/eliminar', ConsultaMedicaDelete.as_view(), name="delete_consultamedica"),
    path('factorderiesgo/<int:pk>/eliminar', FactorDeRiesgoDelete.as_view(), name="delete_factorderiesgo"),
    path('tamizajenutricional/<int:pk>/eliminar', TamizajeNutricionalDelete.as_view(),
         name="delete_tamizajenutricional"),
    path('glucosacapilar/<int:pk>/eliminar', GlucosaCapilarDelete.as_view(), name="delete_glucosacapilar"),
    path('hemoglobinaglucosilada/<int:pk>/eliminar',
         HemoglobinaGlucosiladaDelete.as_view(), name="delete_hemoglobinaglucosilada"),
    path('escalahamilton/<int:pk>/eliminar', EscalaHamiltonDelete.as_view(), name="delete_escalahamilton"),
    path('adherenciatratamiento/<int:pk>/eliminar',
         AdherenciaTratamientoDelete.as_view(), name="delete_adherenciatratamiento"),
    path('evidencias/', EvidenciasList.as_view(), name='evidencias'),
    path('evidencias_json/<int:pk>', EvidenciasListJson.as_view(), name='evidencias_json'),
    path('evidencias/eliminar', EvidenciaDelete.as_view(), name="delete_evidencias"),
    path('evidencias/descargar', EvidenciaDownload.as_view(), name="download_evidencias"),
    path('evaluaciones/', EvaluacionesPlaticasCreate.as_view(),
         name='register_evaluaciones'),

    path('beneficiarios/<int:beneficiario>/nota/registrar', NotaCreate.as_view(),
         name='register_notas'),
    path('nota/<int:nota>',
         NotaView.as_view(), name="view_notas"),
    path('nota/<int:pk>/eliminar', NotaDelete.as_view(), name="delete_notas"),

    path('beneficiarios/<int:beneficiario>/registromensual/registrar', RegistroMensualCreate.as_view(),
         name='register_registromensual'),
    path('registromensual/<int:registromensual>',
         RegistroMensualView.as_view(), name="view_registromensual"),
    path('registromensual/<int:pk>/eliminar',
         RegistroMensualDelete.as_view(), name="delete_registromensual"),
]
